language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
addons:
  apt:
    packages:
    - libfuse-dev
script:
  - cargo build --verbose
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    cargo build --verbose --features=probe
notifications:
  on_success: never
