language: rust
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install fuse libfuse-dev
script:
  - cargo build --verbose
  - cargo test --verbose
notifications:
  on_success: never
