language: rust
rust: nightly # for unstable features
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libfuse-dev
script:
  - cargo build --verbose
notifications:
  on_success: never
